version: "3.1"

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: webserver
    restart: always
    ports:
     - "8000:80"

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth_app
    container_name: auth
    restart: always
    ports:
     - "8001:80"

  github:
    build:
      context: .
      dockerfile: Dockerfile.github_app
    container_name: github
    restart: always
    ports:
     - "8002:80"

  stats:
    build:
      context: .
      dockerfile: Dockerfile.stats_app
    container_name: stats
    restart: always
    ports:
     - "8004:80"


