version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=authDB
      - POSTGRES_USER=userDB
      - POSTGRES_PASSWORD=passwd123
  nginx:
    image: nginx
    build: .
    container_name: webserver
    restart: always
    environment:
      - NGINX_HOST=foobar.com
  auth:
   image: nginx
   restart: always
   ports:
     - "8001:8001"
   links:
     - db
   environment:
      - POSTGRES_DB=authDB
      - POSTGRES_USER=userDB
      - POSTGRES_PASSWORD=passwd123
      - POSTGRES_HOST=db
   depends_on:
     - db
  github:
   image: nginx
   restart: always
   ports:
     - "8002:8002"
   links:
     - db
  aggr:
   image: nginx
   restart: always
   ports:
     - "8004:8004"
   links:
     - db
  web:
   build: .
   restart: always
   ports:
     - "8000:8000"