apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: "/api/auth"
          pathType: Prefix
          backend:
            service:
              name: auth-app
              port:
                number: 80
        - path: "/auth"
          pathType: Prefix
          backend:
            service:
              name: auth-app
              port:
                number: 80
        - path: "/api/github"
          pathType: Prefix
          backend:
            service:
              name: github-app
              port:
                number: 80
        - path: "/github"
          pathType: Prefix
          backend:
            service:
              name: github-app
              port:
                number: 80
        - path: "/api/stats"
          pathType: Prefix
          backend:
            service:
              name: stats-app
              port:
                number: 80
        - path: "/stats"
          pathType: Prefix
          backend:
            service:
              name: stats-app
              port:
                number: 80
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80

