apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: stats
  name: stats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stats
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: stats
    spec:
      containers:
        - args:
            - python3
            - ./main_microservices.py
            - -s
            - stats_app
            - --port
            - "8004"
          env:
            - name: POSTGRES_DB
              value: authDB
            - name: POSTGRES_PASSWORD
              value: passwd123
            - name: POSTGRES_USER
              value: userDB
          image: karolniem/stats
          name: stats
          ports:
            - containerPort: 8004
          resources: {}
          volumeMounts:
            - mountPath: /gtkm
              name: stats-claim0
      restartPolicy: Always
      volumes:
        - name: stats-claim0
          persistentVolumeClaim:
            claimName: stats-claim0
status: {}
